name: Run E2E tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Intalll nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: http://localhost:3000
          NEXT_PUBLIC_API_URL: https://devstore-api-three-xi.vercel.app/
        with:
          build: npm run build
          start: npm start
